app:
  from:
# отделение, пол, возраст, продолжительность, результат, МКБ, профиль койки, кем доставлен, плановая/экстренная, для 14 кс (0, 3, 5, 19, 20, 26, 35, 36, 39, 46)
    baza: 0, 3, 5, 21, 22, 28, 38, 39, 42, 47
#    отделение, пол, возраст, город/село, профиль койки (0, 3, 5, 6, 35)
    post: 0, 3, 5, 6, 38
#    отделение, МКБ, возраст, результат
    secondFormBaza: 0, 28, 5, 22
  to:
    dailyForm:
# Выписано взрослых и пенсионеров, Выписано пенсионеров, Выписано детей, Проведено взрослых и пенсионеров, Проведено пенсионеров, Проведено детей
      firstSheet: 9, 10, 11, 13, 14, 15
# Выписано взрослых и пенсионеров, Проведено взрослых и пенсионеров, Умерло
      secondSheet: 3, 4, 5
# Выписано детей, Проведено детей, Умерло
      thirdSheet: 3, 4, 5
    firstForm:
# ВЫПИСАНО пациентов всего, трудоспособные, дети, старше, УМЕРЛО всего, трудоспособные, дети, старше, ПРОВЕДЕНО всего, трудоспособные, дети, старше
      baza: 10, 25, 11, 12, 14, 26, 15, 16, 17, 27, 18, 19
# Поступило пациентов - всего, из них сельских жителей, 0-17 лет (включительно), трудоспособные, старше трудоспособного возраста
      post: 6, 7, 8, 24, 9
# ТРУДОСПОСОБНЫЕ всего, по экстренным, доставлены скорой, проведено, умерло, ПЕНСИОНЕРЫ всего, по экстренным, доставлены скорой, проведено, умерло, ДЕТИ всего, по экстренным, доставлены скорой, проведено, умерло
    fourteenForm: 3, 4, 5, 6, 8, 13, 14, 15, 16, 18, 23, 24, 25, 27, 31
# все возврасты: выписано, умерло
    secondForm: 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,  24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39
  age:
    woman: 56
    man: 61
  tempValue: 16255.0
  secondFormMkbCodes:
    first: e10, e11, e13, e14
    second: i10, i11, i12, i13
    third: i25
    fourth: j40, j41, j42, j43
    fifth: j44
    sixth: j47
    seventh: j45, j46
logging:
  level:
    com.example.reports: debug
#    com.example.reports.service: debug