app:
  from:
# отделение, пол, возраст, продолжительность, результат, МКБ, профиль койки, кем доставлен, плановая/экстренная, для 14 кс (0, 3, 5, 19, 20, 26, 35, 36, 39, 46)
    baza: 1, 27, 5, 19, 18, 16, 17, 22, 22, 28
#    отделение, пол, возраст, город/село, профиль койки (0, 3, 5, 6, 35)
    post: 6, 15, 12, 13, 10
  to:
    dailyForm:
      firstSheet: 7, 8, 9, 11, 12, 13
      secondSheet: 3, 4, 5
      thirdSheet: 3, 4, 5
    firstForm:
      baza: 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23
      post: 6, 7, 8, 9, 10
    fourteenForm: 3, 4, 5, 6, 8, 13, 14, 15, 16, 18, 23, 24, 25, 27, 31
  age:
    woman: 56
    man: 61
  tempValue: 16255.0
logging:
  level:
    com.example.reports: info
#    com.example.reports.service: debug